# Generated by Django 4.2.4 on 2023-10-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_alter_inmueble_depto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='caracteristicas',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='fotos',
            field=models.ImageField(upload_to='fotos'),
        ),
    ]
