# Generated by Django 4.2.4 on 2023-10-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_alter_inmueble_caracteristicas_alter_inmueble_fotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='fotos',
            field=models.ImageField(blank=True, null=True, upload_to='fotos'),
        ),
    ]
